# -*- coding: utf-8 -*-
"""GraphVis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eJbUXaT8Q1SCtkI1zgGRk-NQrgrJ23D0

**# for Twitter**
"""

pip install graphistry

import graphistry
graphistry.register(api=3, username='pallavi04', password='Hardwork@0405')

import pandas as pd
edges = pd.read_csv('/content/twitter_combined.txt', sep=' ', names=['src', 'dst'])
graphistry.edges(edges, 'src', 'dst').plot()

"""**For Facebook**"""

# PyVis - Facebook data 
import networkx as nx
import matplotlib.pyplot as plt

G =nx.read_edgelist("/content/facebook_combined.txt", create_using = nx.Graph(), nodetype=int)

pip install pyvis

from pyvis.network import Network 
net = Network(notebook=True)
net.from_nx(G)
net.show("facebook.html")